version: "3"
services:
  db:
    image: database
    build: .
    container_name: db
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: kamin124712
      MYSQL_DATABASE: jaid_db
    networks:
       allnetwork:
          ipv4_address: 172.20.0.4
    ports:
      - "3306:3306"
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
