version: "3"
services:
  db:
    image: database
    build: .
    container_name: db
    networks:
       allnetwork:
          ipv4_address: 172.20.0.4
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
